name: Hexo deployer 

on: # 触发条件
  push:
    branches:
      - backup 
      
jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v1 
      
    - name: Use Node.js 10.x 
      uses: actions/setup-node@v1 
      with:
        node-version: "10.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets. HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ HEXO_DEPLOY_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'dakuzai' 
        git config --global user.email 'da_kuzai@163.com'
        # install dependencies
        npm i -g hexo-cli
        npm i
  
    - name: Deploy
      run: |
        hexo generate && hexo douban && hexo deploy 
