# workflow name
name: Hexo Blog CI

# master branch on push, auto run
on: 
  push:
    branches:
      - backup
      
jobs:
  build: 
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: 开始运行
      uses: actions/checkout@v1
      
    # from: https://github.com/actions/setup-node  
    - name: 设置Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: 安装Hexo CI
      run: |
        npm install hexo-cli -g
        npm install
    
    - name: 配置Git环境
      env:
         HEXO_DELOY_KEY: ${{ secrets. HEXO_DELOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ HEXO_DELOY_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'dakuzai' 
        git config --global user.email 'da_kuzai@163.com'
    - name: 部署 Hexo 
      run: |
        rm -rf .deploy_git
        hexo g && hexo douban && hexo deploy
        rm ~/.ssh/id_rsa